apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: ymerflow
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "YmerFlow",
          "Group": "Servers",
          "Host": "postgres.ymerflow.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "ymerflow",
          "Username": "ymerflow",
          "SSLMode": "prefer",
          "PassFile": "/pgpass-data/.pgpass"
        }
      }
    }
